### ISSUE TITLE
he child node "sp_entityid" at path "spid" must be configured.  

### ISSUE THREAD

**Issue by Valamiro** [simevo/spid-symfony3-example#4]
MacBook-Pro-di-Riccardo:spid-symfony3-example_OLD riccardomariani$ php bin/console server:stop

In ArrayNode.php line 230:
                                                                   
  The child node "sp_entityid" at path "spid" must be configured.  
                                                                   

MacBook-Pro-di-Riccardo:spid-symfony3-example_OLD riccardomariani$

**Comment by simevo** [comment]
errore utente
